# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths
reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.0.2
  - OpenZeppelin/openzeppelin-contracts@4.3.3
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.0.2'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.3'
dotenv: .env
# Change to trye to verify smart contracts
verify: False
# set a custom mnemonic for the development network
networks:
  default: mainnet-fork
  mainnet-fork:
    weth_token: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
    dai_token: '0x6b175474e89094c44da98b954eedeac495271d0f'
    uni_router_address: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"